# Generated by Django 4.2.4 on 2023-09-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fashions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=300),
        ),
    ]
